### ISSUE TITLE
Remove unused using-directives

### ISSUE THREAD

**Issue by M-Schiller** [GameLabGraz/Maroon#14]
Right now, Maroon consists of numerous files containing unused using-directives; see
[attached file.](https://github.com/MaroonLab/Maroon/files/2769715/unused-using-directives.txt)

**Comment by michaelholly** [comment]
please update the list with the affected files

**Comment by sandra-bre** [comment]
**Files that I haven't found:**
Assets/MyAssets/Scripts/TaskEntryManager.cs
Assets/Scripts/Assessment/AnswerChoice.cs
Assets/Scripts/Assessment/IAssessmentValue.cs
Assets/Scripts/Assessment/InputQuestion.cs
Assets/Scripts/Assessment/McQuestion.cs
Assets/Scripts/Controller/PendulumManager.cs
Assets/Scripts/Controller/QuestionController.cs
Assets/Scripts/Templates/TTuple.cs
Assets/Scripts/UI/ScriptSlider.cs

**Deleted Files:**
Assets/Scripts/Experiments/BalloonBehaviour.cs

**Files I haven't changed because they belong to a different project:**
Assets/Scripts/Localization/LanguageManager.cs
